"""
This type stub file was generated by pyright.
"""

import proto
from typing import MutableSequence
from google.ai.generativelanguage_v1beta.types import file as gag_file

"""
This type stub file was generated by pyright.
"""
__protobuf__ = ...
class CreateFileRequest(proto.Message):
    r"""Request for ``CreateFile``.

    Attributes:
        file (google.ai.generativelanguage_v1beta.types.File):
            Optional. Metadata for the file to create.
    """
    file: gag_file.File = ...


class CreateFileResponse(proto.Message):
    r"""Response for ``CreateFile``.

    Attributes:
        file (google.ai.generativelanguage_v1beta.types.File):
            Metadata for the created file.
    """
    file: gag_file.File = ...


class ListFilesRequest(proto.Message):
    r"""Request for ``ListFiles``.

    Attributes:
        page_size (int):
            Optional. Maximum number of ``File``\ s to return per page.
            If unspecified, defaults to 10. Maximum ``page_size`` is
            100.
        page_token (str):
            Optional. A page token from a previous ``ListFiles`` call.
    """
    page_size: int = ...
    page_token: str = ...


class ListFilesResponse(proto.Message):
    r"""Response for ``ListFiles``.

    Attributes:
        files (MutableSequence[google.ai.generativelanguage_v1beta.types.File]):
            The list of ``File``\ s.
        next_page_token (str):
            A token that can be sent as a ``page_token`` into a
            subsequent ``ListFiles`` call.
    """
    @property
    def raw_page(self):
        ...
    
    files: MutableSequence[gag_file.File] = ...
    next_page_token: str = ...


class GetFileRequest(proto.Message):
    r"""Request for ``GetFile``.

    Attributes:
        name (str):
            Required. The name of the ``File`` to get. Example:
            ``files/abc-123``
    """
    name: str = ...


class DeleteFileRequest(proto.Message):
    r"""Request for ``DeleteFile``.

    Attributes:
        name (str):
            Required. The name of the ``File`` to delete. Example:
            ``files/abc-123``
    """
    name: str = ...


__all__ = tuple(sorted(__protobuf__.manifest))
