"""
This type stub file was generated by pyright.
"""

from google.protobuf import descriptor as _descriptor

"""
This type stub file was generated by pyright.
"""
_sym_db = ...
DESCRIPTOR = ...
_globals = ...
if _descriptor._USE_C_DESCRIPTORS == False:
    ...
