"""
This type stub file was generated by pyright.
"""

from .async_client import TextServiceAsyncClient
from .client import TextServiceClient

__all__ = ("TextServiceClient", "TextServiceAsyncClient")
