"""
This type stub file was generated by pyright.
"""

import abc
from typing import Mapping, Sequence

"""LLMFnInputsSource."""
NormalizedInputsList = Sequence[Mapping[str, str]]
class LLMFnInputsSource(abc.ABC):
    """Abstract class representing a source of inputs for LLMFunction.

    This class could be extended with concrete implementations that read data
    from external sources, such as Google Sheets.
    """
    def __init__(self) -> None:
        ...
    
    def to_normalized_inputs(self, suppress_status_msgs: bool = ...) -> NormalizedInputsList:
        """Returns a sequence of normalized inputs.

        The return value is a sequence of dictionaries of (placeholder, value)
        pairs, e.g. [{"word": "hot"}, {"word: "cold"}, ....]

        These are used for keyword-substitution for prompts in LLMFunctions.

        Args:
          suppress_status_msgs: If True, suppress status messages regarding the
            input being read.

        Returns:
          A sequence of normalized inputs.
        """
        ...
    


