"""
This type stub file was generated by pyright.
"""

from typing import Sequence
from google.generativeai.notebook import command, ipython_env, model_registry, parsed_args_lib, post_process_utils

"""The compile command."""
class CompileCommand(command.Command):
    """Implementation of the "compile" command."""
    def __init__(self, models: model_registry.ModelRegistry, env: ipython_env.IPythonEnv | None = ...) -> None:
        """Constructor.

        Args:
          models: ModelRegistry instance.
          env: The IPythonEnv environment.
        """
        ...
    
    def execute(self, parsed_args: parsed_args_lib.ParsedArgs, cell_content: str, post_processing_fns: Sequence[post_process_utils.ParsedPostProcessExpr]) -> str:
        ...
    
    def parse_post_processing_tokens(self, tokens: Sequence[Sequence[str]]) -> Sequence[post_process_utils.ParsedPostProcessExpr]:
        ...
    


