"""
This type stub file was generated by pyright.
"""

import pandas
from typing import Sequence
from google.generativeai.notebook import command, ipython_env, parsed_args_lib, post_process_utils

"""The compare command."""
class CompareCommand(command.Command):
    """Implementation of "compare" command."""
    def __init__(self, env: ipython_env.IPythonEnv | None = ...) -> None:
        """Constructor.

        Args:
          env: The IPythonEnv environment.
        """
        ...
    
    def execute(self, parsed_args: parsed_args_lib.ParsedArgs, cell_content: str, post_processing_fns: Sequence[post_process_utils.ParsedPostProcessExpr]) -> pandas.DataFrame:
        ...
    
    def parse_post_processing_tokens(self, tokens: Sequence[Sequence[str]]) -> Sequence[post_process_utils.ParsedPostProcessExpr]:
        ...
    


