"""
This type stub file was generated by pyright.
"""

from typing import Any

"""Convenience functions for writing to and reading from Python variables."""
def validate_var_name(var_name: str) -> None:
    """Validates that the variable name is a valid identifier."""
    ...

def get_main_module(): # -> ModuleType:
    ...

def get_py_var(var_name: str) -> Any:
    """Retrieves the value of `var_name` from the global environment."""
    ...

def has_py_var(var_name: str) -> bool:
    """Returns true if `var_name` is defined in the global environment."""
    ...

def set_py_var(var_name: str, val: Any) -> None:
    """Sets the value of `var_name` in the global environment."""
    ...

