"""
This type stub file was generated by pyright.
"""

"""Private helpers for futures."""
_LOGGER = ...
def start_daemon_thread(*args, **kwargs): # -> Thread:
    """Starts a thread and marks it as a daemon thread."""
    ...

def safe_invoke_callback(callback, *args, **kwargs): # -> None:
    """Invoke a callback, swallowing and logging any exceptions."""
    ...

